name: Ruby tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: WcaOnRails
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
  lint:
    needs: setup-base
    runs-on: ubuntu-latest
    steps:
      - uses: fregante/setup-git-user@v1 # set up dummy user.name and user.email in git so that Overcommit doesn't explode
      - name: Run Overcommit commit hooks
        env:
          BUNDLE_GEMFILE: WcaOnRails/Gemfile
        run: |
          WcaOnRails/bin/bundle exec overcommit --sign
          WcaOnRails/bin/bundle exec overcommit --sign pre-commit
          WcaOnRails/bin/bundle exec overcommit --run
  setup-db:
    needs: setup-base
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql2://root:root@127.0.0.1:3306/wca_test
      RACK_ENV: test
    steps:
      - name: Activate MySQL # as per https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md#mysql
        run: |
          sudo systemctl start mysql.service
      - name: Populate database with seeds
        run: WcaOnRails/bin/bundle exec rake db:reset
  setup-js:
    needs: setup-base
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql2://root:root@127.0.0.1:3306/wca_test
      RACK_ENV: test
    steps:
      - uses: actions/setup-node@v3 # this also includes Yarn
        with:
          node-version: '16'
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules
      - uses: actions/cache@v3
        with:
          path: '~/.cache/yarn'
          key: ${{ runner.os }}-yarn
      - name: Install JS dependencies
        run: WcaOnRails/bin/yarn install
      - name: Pre-compile assets for frontend tests
        env:
          DISABLE_SPRING: 1
        run: |
          WcaOnRails/bin/bundle exec i18n export
          WcaOnRails/bin/bundle exec rake assets:precompile
  test:
    needs: [setup-js, setup-db]
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql2://root:root@127.0.0.1:3306/wca_test
      RACK_ENV: test
    steps:
      - name: Run tests
        id: rspec
        run: WcaOnRails/bin/rspec
      - name: Push coverage data to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: 'WcaOnRails/coverage/lcov/WcaOnRails.lcov'
          base-path: 'WcaOnRails'
      - uses: actions/upload-artifact@v3
        if: always() && steps.rspec.outcome == 'failure'
        with:
          name: capybara-screenshots
          path: WcaOnRails/tmp/capybara
